In [20]:
muckrock_api = 'https://www.muckrock.com/api_v1'

In [22]:
requests.post(
    muckrock_api + '/api/token',    
    data={'username': 'alex2awesome', 'password': 'Pica_pic0'}
)

<Response [404]>

In [101]:
import requests
api_token = '0dfe34a351cff64ab5023ad3524076bdce5f1b27'

In [3]:
def get_headers(token=None):
    if token:
        return {
            'Authorization': 'Token %s' % token,
            'content-type': 'application/json'
        }
    else:
        return {'content-type': 'application/json'}

In [5]:
headers = get_headers(token=api_token)

In [6]:
from getpass import getpass

In [41]:
import pandas as pd 

In [106]:
requests.post(api_domain + '/api/token', data={
    'username': 'alex2awesome',
    'password': 'Pica_pic0'
}, headers=headers)

<Response [429]>

In [116]:
api_domain = 'https://api.www.documentcloud.org'
all_projects = []

next_api = api_domain + '/api/projects'

# 'agenda-watch-bay-area-le-202027'

params = {
    'slug': 'agenda-watch', 
#     'user': ' Chris Stock',
#     'created_at': '2021-03-03'
}

curr_idx = 0

In [117]:
while next_api:
    if curr_idx % 50 == 0:
        print(f'at {curr_idx}...')
        
    projects = requests.get(next_api, headers=headers, params=params)
    res_json = projects.json()
    all_projects += res_json['results']
    next_api = res_json['next']
    curr_idx += 1

at 0...


In [118]:
res_json

{'next': None,
 'previous': None,
 'results': [{'id': 210268,
   'created_at': '2022-10-24T15:11:46.429953Z',
   'description': '',
   'edit_access': False,
   'add_remove_access': False,
   'private': False,
   'slug': 'agenda-watch',
   'title': 'Agenda Watch',
   'updated_at': '2022-10-24T15:11:46.430915Z',
   'user': 20993}]}

In [107]:
project_id = '202027'
end_point = f'/api/projects/{project_id}/documents/'

In [108]:
requests.get(api_domain + end_point,)

<Response [200]>

In [18]:
api_domain + end_point

'https://api.www.documentcloud.org/api/projects/agenda-watch-bay-area-le-202027/documents/'

In [11]:
headers

{'Authorization': 'Token 0dfe34a351cff64ab5023ad3524076bdce5f1b27',
 'content-type': 'application/json'}

# Use Document Cloud Python Client

In [127]:
print(doc_list[0].full_text)

Meeting Minutes
City of Oakland Office of the City Clerk
Oakland City Hall
1 Frank H. Ogawa Plaza
Oakland, California 94612
LaTonda Simmons, City Clerk
Office of the Mayor Annual Recess Agenda
August 1, 2007 - September 4, 2007
Oakland City Hall, 1 Frank H. Ogawa Plaza, Oakland, California, 94612
City of Oakland Website: http://www.oaklandnet.com
Tuesday, August 28, 2007 8:30 AM Oakland City Hall - 3rd Floor
1 Subject: 2007-2008 Real And Personal Property Tax
From: Finance And Management Agency
Recommendation: Adopt A Resolution Fixing The Rate Of Property Tax And Levying A Tax On 
Real And Personal Property In The City Of Oakland For Fiscal Year 2007-2008 For 
Voter-Approved Indebtedness
07-0509
Adopted
View Report.pdf
80794 CMS.pdf
2 Subject: McKillop Roadway - Landslide Damage
From: Public Works Agency
Recommendation: Adopt A Resolution Renewing And Continuing The Local Emergency Due To 
Landslide Damage To McKillop Roadway First Proclaimed By The City Of Oakland On October 
17, 200

In [132]:
from tqdm.auto import tqdm
import time

In [133]:
from documentcloud import DocumentCloud

USERNAME = 'alex2awesome'
PASSWORD = 'Pica_pic0'
project_id = '202027'

client = DocumentCloud(USERNAME, PASSWORD)

project = client.projects.get(project_id)
doc_list = project.document_list
output = []
for doc in tqdm(doc_list):
    document = doc.data
    document['text'] = doc.full_text
    output.append(document)
    time.sleep(1)

  0%|          | 0/1073 [00:00<?, ?it/s]

In [203]:
output_df = pd.DataFrame(output).applymap(lambda x: x[0] if isinstance(x, list) else x)

In [205]:
output_df.to_csv('../data/agenda-watch-bay-area-202027.csv')

# Use Multinomial HMM for Discourse Labels

In [2]:
from transformers import AutoTokenizer
tok = AutoTokenizer.from_pretrained('gpt2')

In [31]:
import sys

In [32]:
sys.path.insert(0, '../scripts/')

In [34]:
import hmm_test

In [9]:
from tqdm.auto import tqdm
import numpy as np

In [66]:
import pandas as pd 
output_df = pd.read_csv('../data/agenda-watch-bay-area-202027.csv')
sentences = output_df['text'].str.split('\n')

In [3]:
text_tokens = sentences.apply(lambda x: list(map(tok.encode, x)))

In [7]:
def tok_list_to_array(tok_list, vocab_size):
    output = np.zeros(vocab_size)
    for tok in tok_list:
        output[tok] += 1
    return output

In [10]:
vocab_size = len(tok.vocab)
doc_lengths = []
X = []
for doc in tqdm(text_tokens):
    doc_lengths.append(len(doc))
    for sent in doc:
        sent_arr = tok_list_to_array(sent, vocab_size)
        X.append(sent_arr)

  0%|          | 0/1073 [00:00<?, ?it/s]

In [27]:
data = np.vstack(X).astype(int)

In [28]:
data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
# Set up model
model = hmm_test.SentenceMultinomialHMM(
    n_components=10,
    n_iter=50,
    init_params='ste'
)


MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [ ]:
model.fit(data, doc_lengths)

In [ ]:
logprob, received = model.decode(data)

# Use HMM With Averaged BERT Embeddings

In [11]:
from tqdm.auto import tqdm
from hmmlearn import vhmm, hmm
import pickle
from transformers import pipeline
extractor = pipeline(model="huawei-noah/TinyBERT_General_4L_312D", task="feature-extraction")

In [82]:
import pandas as pd 
output_df = pd.read_csv('../data/agenda-watch-bay-area-202027.csv')
sentences = output_df['text'].str.split('\n')

In [49]:
doc_sent_embeddings = []
doc_lengths = []
for doc in tqdm(sentences):
    doc_lengths.append(len(doc))
    
    continue
    
    for sent in doc:
        result = extractor(sent, return_tensors=True)
        sent_emb = np.array(result[0]).mean(axis=0)
        doc_sent_embeddings.append(sent_emb)

  0%|          | 0/1073 [00:00<?, ?it/s]

In [88]:
with open('cache/agenda-watch-embeddings.pkl', 'wb') as f:
    pickle.dump(doc_sent_embeddings, f)

In [7]:
with open('cache/agenda-watch-embeddings.pkl', 'rb') as f:
    doc_sent_embeddings = pickle.load(f)

In [40]:
from tqdm.auto import tqdm

In [47]:
class VariationalGaussianHMMWithTQDM(vhmm.VariationalGaussianHMM):
    def fit(self, X, lengths=None):
        X = check_array(X)
        if lengths is None:
            lengths = np.asarray([X.shape[0]])
        self._init(X, lengths)
        self._check()
        self.monitor_._reset()
        for iter in tqdm(range(self.n_iter)):
            stats, curr_logprob = self._do_estep(X, lengths)
            lower_bound = self._compute_lower_bound(curr_logprob)
            self._do_mstep(stats)
            self.monitor_.report(lower_bound)
            if self.monitor_.converged:
                break

            if (self.transmat_.sum(axis=1) == 0).any():
                _log.warning("Some rows of transmat_ have zero sum because no "
                             "transition from the state was ever observed.")
        return 

In [45]:
from sklearn.utils import check_array

In [113]:
model = VariationalGaussianHMMWithTQDM(
     n_components=5,
     n_iter=50,
#      covariance_type="full",
#      implementation="scaling",
#      tol=1e-6,
     verbose=True
)

if False:
    model = hmm.GaussianHMM(
         n_components=5,
         n_iter=50,
    #      covariance_type="full",
         implementation="scaling",
    #      tol=1e-6,
         verbose=True
    )

In [ ]:
n_docs = None
model.fit(data[:sum(doc_lengths[:n_docs])], doc_lengths[:n_docs])

# Try Clustering with KMeans

In [74]:
from sklearn.cluster import KMeans
import numpy as np
from more_itertools import flatten
import pandas as pd 

In [101]:
kmeans = KMeans(n_clusters=5).fit(data)

In [102]:
clusters = kmeans.predict(data)

In [103]:
sentences_df = pd.Series(list(flatten(sentences))).to_frame('sents')

In [104]:
sentences_df['cluster'] = clusters

In [111]:
sentences_df.loc[lambda df: df['cluster'] == 4]['sents'].value_counts()

Oakland, California 94612                                                 175
San Francisco, CA 94102-4689                                              160
10:00 AM                                                                  107
San Francisco, CA 94105                                                    54
1:00 PM                                                                    50
                                                                         ... 
TUESDAY, JANUARY 16, 2018– 6:15 P.M.                                      1
City and County of San Francisco Page 1 Printed at 1:34 pm on 12/24/12      1
991909                                                                      1
991908                                                                      1
City of Sunnyvale Page 1 Printed on 1/16/2020                               1
Name: sents, Length: 5280, dtype: int64

### Example

In [ ]:
def sentence2counts(sentence):
    ans = []
    for word, idx in vocab2id.items():
        count = sentence.count(word)
        ans.append(count)
    return ans

In [134]:
import numpy as np
from hmmlearn import hmm

# For this example, we will model the stages of a conversation,
# where each sentence is "generated" with an underlying topic, "cat" or "dog"
states = ["cat", "dog"]
id2topic = dict(zip(range(len(states)), states))
# we are more likely to talk about cats first
start_probs = np.array([0.6, 0.4])

# For each topic, the probability of saying certain words can be modeled by
# a distribution over vocabulary associated with the categories

vocabulary = ["tail", "fetch", "mouse", "food"]
# if the topic is "cat", we are more likely to talk about "mouse"
# if the topic is "dog", we are more likely to talk about "fetch"
emission_probs = np.array([[0.25, 0.1, 0.4, 0.25],
                           [0.2, 0.5, 0.1, 0.2]])

# Also assume it's more likely to stay in a state than transition to the other
trans_mat = np.array([[0.8, 0.2], [0.2, 0.8]])

# Pretend that every sentence we speak only has a total of 5 words,
# i.e. we independently utter a word from the vocabulary 5 times per sentence
# we observe the following bag of words (BoW) for 8 sentences:
observations = [
    ["tail", "mouse", "mouse", "food", "mouse"],
    ["food", "mouse", "mouse", "food", "mouse"],
    ["tail", "mouse", "mouse", "tail", "mouse"],
    ["food", "mouse", "food", "food", "tail"],
    ["tail", "fetch", "mouse", "food", "tail"],
    ["tail", "fetch", "fetch", "food", "fetch"],
    ["fetch", "fetch", "fetch", "food", "tail"],
    ["food", "mouse", "food", "food", "tail"],
    ["tail", "mouse", "mouse", "tail", "mouse"],
    ["fetch", "fetch", "fetch", "fetch", "fetch", "fetch"]
]

# Convert "sentences" to numbers:
vocab2id = dict(zip(vocabulary, range(len(vocabulary))))
X = []
for sentence in observations:
    row = sentence2counts(sentence)
    X.append(row)

data = np.array(X, dtype=int)

# pretend this is repeated, so we have more data to learn from:
lengths = [len(X)]*5
sequences = np.tile(data, (5,1))

In [189]:
# Set up model:
model = SentenceMultinomialHMM2(
    n_components=len(states),
    n_iter=50,
    init_params='ste'
)

model.fit(sequences, lengths)

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


SentenceMultinomialHMM2(n_components=2, n_iter=50,
                        random_state=RandomState(MT19937) at 0x7F85A9DCF740)

In [192]:
model.fit(sequences, lengths)
logprob, received = model.decode(sequences)

print("Topics discussed:")
print([id2topic[x] for x in received])

print("Learned emission probs:")
print(model.emissionprob_)

print("Learned transition matrix:")
print(model.transmat_)

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'


Topics discussed:
['cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog']
Learned emission probs:
[[2.57134386e-01 2.86295346e-02 4.28529613e-01 2.85706466e-01]
 [1.24992633e-01 7.50014271e-01 7.48807992e-06 1.24985608e-01]]
Learned transition matrix:
[[0.71431126 0.28568874]
 [0.50015702 0.49984298]]
